apiVersion: v1
kind: ConfigMap
metadata:
  name: posttechfiap-api-config
data:
  ASPNETCORE_URLS: "http://*:8080;https://*:8443"
  ASPNETCORE_Kestrel__Certificates__Default__Path: "/app/certificate.pfx"